sudo: required
language: minimal
services:
 - docker

install:
 - docker build --tag vanetza/travis tools/docker

script:
 - docker run -v$TRAVIS_BUILD_DIR:/home/build-user/workspace:ro vanetza/travis
